[build]
  publish = "."
  command = "echo static site"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache"
